sudo: false
dist: trusty

language: php

notifications:
  email:
    on_success: never
    on_failure: change

branches:
  only:
    - master
    - /^(?>\.{1}|\d+)*/ # capture tags (1.2.3)

env:
  global:
    - PATH="$TRAVIS_BUILD_DIR/vendor/bin:$PATH"
    - WP_CLI_BIN_DIR="$TRAVIS_BUILD_DIR/vendor/bin"

matrix:
  include:
    - php: 7.2
      env: WP_VERSION=latest
    - php: 7.1
      env: WP_VERSION=latest
    - php: 5.6
      env: WP_VERSION=latest
    - php: 5.6
      env: WP_VERSION=4.9.9
    - php: 5.6
      env: WP_VERSION=trunk
    - php: 5.6
      env: WP_TRAVISCI=phpcs
  allow_failures:
    - php: 5.6
      env: WP_TRAVISCI=phpcs

before_script:
  - export PATH="$HOME/.config/composer/vendor/bin:$PATH"
  - |
    if [[ ! -z "$WP_VERSION" ]] ; then
      bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
      composer global require "phpunit/phpunit=4.8.*|5.7.*"
    fi
  - |
    if [[ "$WP_TRAVISCI" == "phpcs" ]] ; then
      composer global require wp-coding-standards/wpcs
      phpcs --config-set installed_paths $HOME/.config/composer/vendor/wp-coding-standards/wpcs
    fi

script:
  - |
    if [[ ! -z "$WP_VERSION" ]] ; then
      phpunit
      WP_MULTISITE=1 phpunit
    fi
  - |
    if [[ "$WP_TRAVISCI" == "phpcs" ]] ; then
      phpcs
    fi

before_deploy:
  # Zip up the plugin
  - zip -r sign-in-with-google.zip src/sign-in-with-google

deploy:
  # Upload .zip to Github release
  - provider: releases
    api_key: "$GITHUB_OAUTH_TOKEN"
    file: "sign-in-with-google.zip"
    skip_cleanup: true
    on:
      tags: true
      php: 7.2

  # Auto-deploys the built plugin to WordPress.org
  - provider: script
    skip_cleanup: true
    script:
      - php build/plugin-build $WP_ORG_PASSWORD $WP_ORG_USERNAME sign-in-with-google
    on:
      tags: true
      php: 7.2
